print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/uyendien/Monash/Unity/memory-lane/Memory Lane Unity Final/Assets/Meshes/Gallery/LightingFix1.mb"`)
{		
	file -o "/Users/uyendien/Monash/Unity/memory-lane/Memory Lane Unity Final/Assets/Meshes/Gallery/LightingFix1.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/uyendien/Monash/Unity/memory-lane/Memory Lane Unity Final/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/uyendien/Monash/Unity/memory-lane/Memory Lane Unity Final/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/uyendien/Monash/Unity/memory-lane/Memory Lane Unity Final/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
